Pin python dependencies with Poetry (#120)
Ported from https://github.com/canonical/mysql-k8s-operator/pull/273

diff --git a/charmcraft.yaml b/charmcraft.yaml
--- a/charmcraft.yaml
+++ b/charmcraft.yaml
@@ -11,11 +11,19 @@ bases:
         channel: "22.04"
 parts:
   charm:
+    override-pull: |
+      craftctl default
+      if [[ ! -f requirements.txt ]]
+      then
+          echo 'ERROR: Use "tox run -e build" instead of calling "charmcraft pack" directly' >&2
+          exit 1
+      fi
     charm-entrypoint: src/kubernetes_charm.py
     charm-binary-python-packages:
       - mysql-connector-python~=8.0.32
     build-packages:
       - libffi-dev
       - libssl-dev
+      - pkg-config
       - rustc
       - cargo
